chore: run `cargo update`
Before this, the build was failing with the following error:

error[E0635]: unknown feature `stdsimd`
  --> /home/tdeo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.6/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

It's weird that old nightly features in dependencies can cause your
build to break, but oh well.